/obj/structure/closet/maintenance
	name = "abandoned closet"
	desc = "An old, forgotten, and unwanted closet."
	icon_state = "maint"
	icon_closed = "maint"
	icon_opened = "maintopen"

/obj/structure/closet/maintenance/contained/New()
	..()
	if(prob(90))
		new /obj/random/junk(src)
	if(prob(80))
		new /obj/random/junk(src)
	if(prob(70))
		new /obj/random/junk(src)
	if(prob(60))
		new /obj/random/junk(src)
	if(prob(50))
		new /obj/random/trash(src)
	if(prob(40))
		new /obj/random/junk(src)
	if(prob(30))
		new /obj/random/junk(src)
	if(prob(20))
		new /obj/random/junk(src)
	if(prob(10))
		new /obj/random/junk(src)

/obj/structure/closet/maintenance/closet
	icon_state = "maintcloset"
	icon_closed = "maintcloset"
	icon_opened = "maintclosetopen"

/obj/structure/closet/maintenance/closet/contained/New()
	..()
	if(prob(90))
		new /obj/random/junk(src)
	if(prob(80))
		new /obj/random/plushie(src)
	if(prob(70))
		new /obj/random/junk(src)
	if(prob(60))
		new /obj/random/tech_supply(src)
	if(prob(50))
		new /obj/random/trash(src)
	if(prob(40))
		new /obj/random/snack(src)
	if(prob(30))
		new /obj/random/action_figure(src)
	if(prob(20))
		new /obj/random/drinkbottle(src)
	if(prob(10))
		new /obj/random/junk(src)

/obj/structure/closet/maintenance/medical
	icon_state = "maintmedical"
	icon_closed = "maintmedical"
	icon_opened = "maintmedicalopen"

/obj/structure/closet/maintenance/medical/contained/New()
	..()
	if(prob(90))
		new /obj/random/junk(src)
	if(prob(70))
		new /obj/item/clothing/suit/storage/toggle/labcoat(src)
	if(prob(60))
		new /obj/item/clothing/gloves/latex/nitrile(src)
	if(prob(60))
		new /obj/item/clothing/mask/surgical(src)
	if(prob(50))
		new /obj/random/trash(src)
	if(prob(50))
		new /obj/random/junk(src)
	if(prob(40))
		new /obj/item/storage/box/autoinjectors(src)
	if(prob(40))
		new /obj/item/clothing/accessory/storage/white_vest/alt(src)
	if(prob(30))
		new /obj/item/storage/box/syringes(src)
	if(prob(30))
		new /obj/random/junk(src)
	if(prob(20))
		new /obj/random/firstaid(src)

/obj/structure/closet/maintenance/medicalalt
	icon_state = "maintmedicalalt"
	icon_closed = "maintmedicalalt"
	icon_opened = "maintmedicalaltopen"

/obj/structure/closet/maintenance/medicalalt/contained/New()
	..()
	if(prob(90))
		new /obj/random/junk(src)
	if(prob(75))
		new /obj/random/medical/lite(src)
	if(prob(75))
		new /obj/random/pill(src)
	if(prob(50))
		new /obj/random/trash(src)
	if(prob(50))
		new /obj/random/junk(src)
	if(prob(50))
		new /obj/random/medical/lite(src)
	if(prob(50))
		new /obj/random/pill(src)
	if(prob(25))
		new /obj/random/medical/lite(src)
	if(prob(25))
		new /obj/random/pill(src)
	if(prob(20))
		new /obj/random/junk(src)
	if(prob(3))
		new /obj/item/reagent_containers/hypospray/autoinjector/combatpain(src)

/obj/structure/closet/maintenance/fridge
	name = "abandoned fridge"
	desc = "An old, forgotten, and unwanted fridge. Not the best place to store food."
	icon_state = "maintfridge"
	icon_closed = "maintfridge"
	icon_opened = "maintfridgeopen"

/obj/structure/closet/maintenance/fridge/contained/New()
	..()
	if(prob(90))
		new /obj/random/junk(src)
	if(prob(90))
		new /obj/random/snack(src)
	if(prob(60))
		new /obj/random/snack(src)
	if(prob(60))
		new /obj/item/reagent_containers/food/packaged/sosjerky(src)
	if(prob(50))
		new /obj/random/trash(src)
	if(prob(50))
		new /obj/random/junk(src)
	if(prob(50))
		new /obj/item/reagent_containers/food/meat/monkey(src)
	if(prob(50))
		new /obj/item/reagent_containers/food/cheesewedge(src)
	if(prob(50))
		new /obj/item/reagent_containers/food/packaged/nutribar(src)
	if(prob(40))
		new /obj/item/reagent_containers/food/packaged/hematogen(src)
	if(prob(30))
		new /obj/random/snack(src)
	if(prob(30))
		new /obj/random/junk(src)
	if(prob(5))
		new /obj/item/material/knife/butch/kitchen(src)
	if(prob(5))
		new /obj/item/reagent_containers/food/meat/human(src)

/obj/structure/closet/maintenance/cargo
	icon_state = "maintcargo"
	icon_closed = "maintcargo"
	icon_opened = "maintcargoopen"

/obj/structure/closet/maintenance/cargo/contained/New()
	..()
	if(prob(90))
		new /obj/random/junk(src)
	if(prob(75))
		new /obj/item/storage/box(src)
	if(prob(75))
		new /obj/item/pen/multi(src)
	if(prob(60))
		new /obj/item/clothing/accessory/armband/cargo(src)
	if(prob(60))
		new /obj/item/clothing/gloves/thick(src)
	if(prob(50))
		new /obj/random/trash(src)
	if(prob(50))
		new /obj/random/junk(src)
	if(prob(50))
		new /obj/item/storage/backpack/dufflebag(src)
	if(prob(40))
		new /obj/item/tape_roll(src)
	if(prob(40))
		new /obj/item/packageWrap(src)
	if(prob(30))
		new /obj/random/smokes(src)

/obj/structure/closet/maintenance/security
	icon_state = "maintsec"
	icon_closed = "maintsec"
	icon_opened = "maintsecopen"

/obj/structure/closet/maintenance/security/contained/New()
	..()
	if(prob(90))
		new /obj/random/junk(src)
	if(prob(80))
		new /obj/item/storage/secure/briefcase(src)
	if(prob(60))
		new /obj/item/cell/device/high(src)
	if(prob(50))
		new /obj/random/trash(src)
	if(prob(50))
		new /obj/random/junk(src)
	if(prob(40))
		new /obj/item/clothing/accessory/storage/black_vest/alt(src)
	if(prob(30))
		new /obj/item/storage/box/security(src)
	if(prob(25))
		new /obj/item/grenade/smokebomb(src)
	if(prob(25))
		new /obj/item/device/flashlight/maglight(src)
	if(prob(10))
		new /obj/item/clothing/head/helmet(src)
	if(prob(10))
		new /obj/item/clothing/suit/armor/vest(src)
	if(prob(5))
		new /obj/item/storage/secure/briefcase/money(src)
	if(prob(1))
		new /obj/item/melee/baton(src)

/obj/structure/closet/maintenance/science
	icon_state = "maintscience"
	icon_closed = "maintscience"
	icon_opened = "maintscienceopen"

/obj/structure/closet/maintenance/science/contained/New()
	..()
	if(prob(90))
		new /obj/random/junk(src)
	if(prob(60))
		new /obj/item/circuitboard/protolathe(src)
	if(prob(50))
		new /obj/random/trash(src)
	if(prob(50))
		new /obj/random/junk(src)
	if(prob(50))
		new /obj/item/stack/material/glass/ten(src)
	if(prob(50))
		new /obj/item/stack/material/steel/ten(src)
	if(prob(30))
		new /obj/item/clothing/glasses/hud/standard/science(src)
	if(prob(15))
		new /obj/item/rcd_upgrade/anti_interrupt(src)
	if(prob(15))
		new /obj/item/rcd_upgrade/cooling(src)
	if(prob(15))
		new /obj/item/rcd_upgrade/frames(src)
	if(prob(15))
		new /obj/item/rcd_upgrade/furnishing(src)
	if(prob(15))
		new /obj/item/rcd_upgrade/simple_circuits(src)
	if(prob(5))
		new /obj/item/cell/infinite(src)

/obj/structure/closet/maintenance/hydro
	icon_state = "mainthydro"
	icon_closed = "mainthydro"
	icon_opened = "mainthydroopen"

/obj/structure/closet/maintenance/hydro/contained/New()
	..()
	if(prob(90))
		new /obj/random/junk(src)
	if(prob(80))
		new /obj/item/clothing/accessory/armband/hydro(src)
	if(prob(70))
		new /obj/item/clothing/gloves/thick/botany(src)
	if(prob(60))
		new /obj/item/storage/plants(src)
	if(prob(60))
		new /obj/item/material/minihoe(src)
	if(prob(60))
		new /obj/item/device/analyzer/plant_analyzer(src)
	if(prob(50))
		new /obj/random/trash(src)
	if(prob(50))
		new /obj/random/junk(src)
	if(prob(40))
		new /obj/item/material/hatchet(src)
	if(prob(30))
		new /obj/item/reagent_containers/vessel/plastic/eznutrient(src)
	if(prob(30))
		new /obj/item/reagent_containers/vessel/plastic/robustharvest(src)
	if(prob(30))
		new /obj/item/reagent_containers/vessel/plastic/left4zed(src)
	if(prob(25))
		new /obj/structure/flora/pottedplant/dead(src)
	if(prob(15))
		new /obj/item/seeds/random(src)
	if(prob(10))
		new /obj/item/seeds/random(src)
	if(prob(5))
		new /obj/item/seeds/random(src)

/obj/structure/closet/maintenance/engineering
	icon_state = "mainteng"
	icon_closed = "mainteng"
	icon_opened = "maintengopen"

/obj/structure/closet/maintenance/engineering/contained/New()
	..()
	if(prob(90))
		new /obj/random/junk(src)
	if(prob(80))
		new /obj/item/clothing/gloves/insulated/cheap(src)
	if(prob(70))
		new /obj/item/clothing/head/beret/engineering(src)
	if(prob(60))
		new /obj/item/clothing/mask/gas(src)
	if(prob(50))
		new /obj/item/device/flashlight/upgraded(src)
	if(prob(50))
		new /obj/random/toolbox(src)
	if(prob(50))
		new /obj/random/trash(src)
	if(prob(50))
		new /obj/random/junk(src)
	if(prob(40))
		new /obj/item/storage/belt/utility(src)
	if(prob(40))
		new /obj/item/clothing/accessory/storage/brown_vest/alt(src)
	if(prob(30))
		new /obj/item/device/multitool(src)
	if(prob(10))
		new /obj/item/clothing/gloves/insulated(src)
	if(prob(3))
		new /obj/item/clothing/suit/space/void/engineering/alt/prepared(src)

/obj/structure/closet/maintenance/bio
	icon_state = "maintbio"
	icon_closed = "maintbio"
	icon_opened = "maintbioopen"

/obj/structure/closet/maintenance/bio/contained/New()
	..()
	if(prob(90))
		new /obj/random/junk(src)
	if(prob(75))
		new /obj/item/clothing/head/bio_hood/general(src)
	if(prob(75))
		new /obj/item/clothing/suit/bio_suit/general(src)
	if(prob(50))
		new /obj/random/trash(src)
	if(prob(50))
		new /obj/random/junk(src)
	if(prob(50))
		new /obj/item/clothing/mask/gas/clear(src)
	if(prob(50))
		new /obj/item/tank/emergency/oxygen/double(src)
	if(prob(40))
		new /obj/item/storage/box/masks(src)
	if(prob(40))
		new /obj/item/storage/box/gloves(src)
	if(prob(30))
		new /obj/item/storage/box/syringes(src)
	if(prob(15))
		new /obj/item/clothing/glasses/hud/one_eyed/oneye/medical(src)
	if(prob(15))
		new /obj/random/firstaid(src)

/obj/structure/closet/maintenance/nanotrasen
	desc = "A forgotten and unwanted closet. Looks stylish enough for its age."
	icon_state = "maintnt"
	icon_closed = "maintnt"
	icon_opened = "maintntopen"

/obj/structure/closet/maintenance/nanotrasen/contained/New()
	..()
	if(prob(90))
		new /obj/random/junk(src)
	if(prob(80))
		new /obj/item/device/radio/headset(src)
	if(prob(75))
		new /obj/item/cane(src)
	if(prob(75))
		new /obj/item/clothing/head/soft/sec/corp/guard(src)
	if(prob(75))
		new /obj/item/clothing/accessory/armband/whitered(src)
	if(prob(60))
		new /obj/item/storage/briefcase(src)
	if(prob(60))
		new /obj/item/book/wiki/chain_of_command(src)
	if(prob(60))
		new /obj/item/book/wiki/nt_regs(src)
	if(prob(50))
		new /obj/random/trash(src)
	if(prob(50))
		new /obj/random/junk(src)
	if(prob(50))
		new /obj/item/clothing/under/track_pants/trackpantswhite(src)
	if(prob(50))
		new /obj/item/clothing/gloves/white(src)
	if(prob(50))
		new /obj/item/clothing/shoes/white(src)
	if(prob(40))
		new /obj/item/storage/backpack/nanotrasen(src)
	if(prob(40))
		new /obj/item/storage/photo_album(src)
	if(prob(40))
		new /obj/random/drinkbottle(src)
	if(prob(15))
		new /obj/item/clothing/accessory/holster/thigh(src)
	if(prob(10))
		new /obj/item/clothing/suit/armor/pcarrier/light/budget(src)
